---
- name:
  hosts: all
  become: true
  vars: 
    git_repository: "https://github.com/michalpartyka/Ansible_roles"
    git_branch: "main"
  tasks:
    - name: create folder
      file:
        path: /etc/ansible/roles
        state: directory
        mode: '0755'
    - name: git checkout
      git:
        repo: "{{ git_repository }}"
        dest: "/etc/ansible/roles"
        version: "{{ git_branch }}"        
